version: '2'

services:
  web:
    build: .
    image: caseyfw/blog
    depends_on:
      - db
    ports:
      - "80:80"
    environment:
      DATABASE_URL: mysql://user:password@db:3306/blog
    volumes:
      - .:/app

  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: blog
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: super-secret-password
